import React, { useEffect } from 'react'
import styled from 'styled-components'
import { useSettingStore } from '../setting/setting-store'
import { LLMProviderSelector } from '../../components/themed-ui/selector/llm-provider-selector'
import { useQuizStore } from './quiz-store'

const Container = styled.header`
  height: 52px;
  padding: 10px 0;
  display: flex;
  justify-content: end;
  align-items: center;
`

const StyledSelect = styled(LLMProviderSelector)`
  min-width: 100px;
  display: inline-block;
  margin-left: 10px;
`

export const QuizPageHeader: React.FC = () => {
  const availableLLMProviders = useSettingStore.use.availableLLMProviders()
  const selected = useQuizStore.use.selectedLLMProvider()

  useEffect(() => {
    // select 1 provider if we've got any available providers
    if (availableLLMProviders.length) {
      useQuizStore.setState({
        selectedLLMProvider: availableLLMProviders[0],
      })
    }
  }, [availableLLMProviders])

  return (
    <Container>
      <span>Generated by</span>
      <StyledSelect
        availableProviders={availableLLMProviders}
        onSelect={(provider) => {
          useQuizStore.setState({
            selectedLLMProvider: provider,
          })
        }}
        value={selected}
      />
    </Container>
  )
}
