export const ECDICT_PREFIX = 'ECDICT';

export enum EcDictChannel {
  FETCH_AVAILABLE = 'ECDICT/FETCH_AVAILABLE',
  FETCH_SUGGESTS = 'ECDICT/FETCH_SUGGESTS',
  FETCH_RESULT = 'ECDICT/FETCH_RESULT',
  FETCH_RESULT_BATCH = 'ECDICT/FETCH_RESULT_BATCH',
}
