export const LOCAL_DB_NOTE_PREFIX = 'LOCAL_DB_NOTE';
export const LOCAL_DB_HISTORY_PREFIX = 'LOCAL_DB_HISTORY';
export const LOCAL_DB_PREFIX = 'LOCAL_DB';

enum LocalDbNoteChannel {
  ADD_HISTORY = 'LOCAL_DB_NOTE/ADD_HISTORY',
  FETCH = 'LOCAL_DB_NOTE/FETCH',
  FETCH_LATEST = 'LOCAL_DB_NOTE/FETCH_LATEST',
  SYNC_HISTORY = 'LOCAL_DB_NOTE/SYNC_HISTORY',
}

enum LocalDbHistoryChannel {
  ADD = 'LOCAL_DB_HISTORY/ADD',
  FIND_ALL = 'LOCAL_DB_HISTORY/FIND_ALL',
  LIST = 'LOCAL_DB_HISTORY/LIST',
  SEARCH_BY_CREATE_AT = 'LOCAL_DB_HISTORY/SEARCH_BY_CREATE_AT',
  SEARCH_BY_UPDATE_AT = 'LOCAL_DB_HISTORY/SEARCH_BY_UPDATE_AT',
  FETCH_SOURCE_SUGGEST = 'LOCAL_DB_HISTORY/FETCH_SOURCE_SUGGEST',
}

enum LocalDbChannel {
  INIT = 'LOCAL_DB/INIT',
  FETCH_AVAILABLE = 'LOCAL_DB/FETCH_AVAILABLE'
}

export {
  LocalDbChannel,
  LocalDbNoteChannel,
  LocalDbHistoryChannel,
};

