enum SearchChannel {
  TOGGLE_PIN_SEARCH_WINDOW = 'TOGGLE_PIN_SEARCH_WINDOW',
  TOGGLE_SEARCH_WINDOW = 'TOGGLE_SEARCH_WINDOW',
  SHOW_SEARCH_WINDOW = 'SHOW_SEARCH_WINDOW',
  HIDE_SEARCH_WINDOW = 'HIDE_SEARCH_WINDOW',
  TOP_SEARCH_WINDOW = 'TOP_SEARCH_WINDOW',
  SEARCH = 'SEARCH',
}

export { SearchChannel };
