export namespace SyncHistoryChannel {
  export enum Command {
    // start in background
    SYNC_SEARCH_HISTORY_COMMAND_START_SILENTLY = 'SYNC_SEARCH_HISTORY_COMMAND_START_SILENTLY',
  }

  export enum Event {
    SYNC_SEARCH_HISTORY_EVENT_STARTED = 'SYNC_SEARCH_HISTORY_EVENT_STARTED',
    SYNC_SEARCH_HISTORY_EVENT_PROGRESS = 'SYNC_SEARCH_HISTORY_EVENT_PROGRESS',
    SYNC_SEARCH_HISTORY_EVENT_ERROR = 'SYNC_SEARCH_HISTORY_EVENT_ERROR',
    SYNC_SEARCH_HISTORY_EVENT_FINISHED = 'SYNC_SEARCH_HISTORY_EVENT_FINISHED',
  }
}
