import * as electron from 'electron';

export const Runtime = {
  isRenderer,
  isDev: isDev(),
  platform: getPlatform(),
  isMac: isMac(),
  process: getProcess(),
};

function isRenderer() {
  // running in a web browser
  if (typeof process === 'undefined') return true;

  // node-integration is disabled
  if (!process) return true;

  // We're in node.js somehow
  if (!process.type) return false;

  if(process.argv.includes('--app-path=/Users/xy/Workspace/code/personal/noob-dict/noob-dict-desktop/node_modules/@jest-runner/electron/build')) {
    // jest runner
    return false;
  }

  return process.type === 'renderer';
}

function isDev(): boolean {
  if (isRenderer()) {
    const remote = require('@electron/remote');
    return !remote.app.isPackaged;
  } else {
    if (!electron.app) {
      // jest runner
      return true;
    }
    return !electron.app.isPackaged;
  }
}

/**
 * Note that if you want to access env values
 * generated by dotenv in renderer process.
 * you should use process.env directly.
 */
function getProcess(): NodeJS.Process {
  if (isRenderer()) {
    const remote = require('@electron/remote');
    return remote.process;
  } else {
    return process;
  }
}

function getPlatform(): NodeJS.Platform {
  return getProcess().platform
}

function isMac(): boolean {
  return getPlatform() === 'darwin'
}
