# if push dev branch
# we execute this workflow
name: build

on:
  push:
    branches:
      - dev

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} - ${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: install npm packages
        run: yarn

      - name: vite build
        run: yarn vite:build

      - name: build electron
        if: runner.os != 'macOS'
        run: yarn electron:build

      - name: build electron mac
        if: runner.os == 'macOS'
        run: yarn electron:build --mac --x64 --arm64
